Convert to Side Panel View
RabbyHub/Rabby pull request #2498
Opened 2024-08-29 20:42 UTC by passabilities

Using Chrome extension feature to display as a side panel instead of the default popup.

Closes #2159

2024-11-07 04:43 UTC, passabilities commented
@vvvvvv1vvvvvv is this something that could potentially get merged in? what are your thoughts?

2024-12-12 23:11 UTC, CreeTar requested changes
just my 2 cents, though i am not a react-guru, but i really want that sidebar ;)

2025-02-10 23:16 UTC, closed without merging

2025-03-15 17:24 UTC, passabilities commented on src/ui/views/Dashboard/components/CurrentConnection/index.tsx
> +      chrome.runtime.onMessage.removeListener(handleTabUpdate);
Adding `clearInterval()` to the cleanup function and if the effect is called multiple times cause the `windowId` then the cleanup function should be sufficient.

2025-03-15 18:02 UTC, passabilities commented on src/ui/views/Dashboard/components/CurrentConnection/index.tsx
> +      chrome.runtime.onMessage.removeListener(handleTabUpdate);
I think I can delete the interval